workflows:
  flutter-release-build:
    name: Flutter Signed Release APK
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        CM_KEYSTORE_PATH: keystore.jks

    scripts:
      - name: Decode and save the keystore
        script: echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH

      - name: Build signed release APK
        script: |
          flutter pub get
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
